import React, { createContext, useState, useContext } from 'react'

const translations = {
    vi: {
        welcome: "Chào mừng đến với dự án FreeTime Spots",
        login: "Đăng nhập",
        email: "Địa chỉ Email",
        password: "Mật khẩu",
        confirm_password: "Xác nhận mật khẩu",
        forgot_password: "Quên mật khẩu?",
        reset_password: "Đặt lại mật khẩu",
        reset_password_failed: "Đặt lại mật khẩu thất bại",
        new_password: "Mật khẩu mới",
        change_password: "Đổi mật khẩu",
        register: "Đăng ký",
        don_t_have_account: "Chưa có tài khoản?",
        already_have_account: "Đã có tài khoản?",
        please_enter_email: "Vui lòng nhập địa chỉ email liên kết với tài khoản của bạn.",
        otp_note: "Mã OTP sẽ được gửi đến địa chỉ email đã đăng ký của bạn.",
        get_otp: "Lấy mã OTP",
        get_otp_failed: "Lấy mã OTP thất bại",
        invalid_otp: "Mã OTP không hợp lệ",
        home: "Trang chủ",
        schedule: "Lịch trình",
        map: "Bản đồ",
        my_page: "Trang của tôi",
        check_email: "Vui lòng kiểm tra email của bạn",
        enter_otp_sent_to: (email) => `Nhập mã OTP đã gửi đến ${email}`,
        verify: "Xác minh",
        did_not_receive_code: "Không nhận được mã?",
        resend_code: "Gửi lại mã",
        enter_new_password: "Nhập mật khẩu mới của bạn",
        remember_password: "Đã nhớ mật khẩu? ",
        change_password_success: "Đổi mật khẩu thành công",
        change_password_failed: "Đổi mật khẩu thất bại",
        change_password_process_success: "Quá trình đặt lại mật khẩu hoàn tất thành công",
        password_not_match: "Mật khẩu xác nhận không khớp với mật khẩu mới",
        back_to_login: "Quay lại đăng nhập",
        where_you_go: "Bạn sẽ đi đâu? ",
        more: "Xem thêm",
        less: "Thu gọn",
        gym: "Gym",
        yoga: "Yoga",
        pilates: "Pilates",
        crossfit: "Crossfit",
        boxing: "Boxing",
        running: "Chạy bộ",
        swimming: "Bơi lội",
        cycling: "Đạp xe",
        bouldering: "Leo núi trong nhà",
        golf: "Golf",
        badminton: "Cầu lông",
        tennis: "Tennis",
        table_tennis: "Bóng bàn",
        basketball: "Bóng rổ",
        soccer: "Bóng đá",
        volleyball: "Bóng chuyền",
        suggest_list: "Danh sách gợi ý",
        order: "Thứ tự",
        search: "Tìm kiếm",
        type: "Thể Loại",
        distance: "Khoảng cách",
        from_work: "Từ chỗ làm",
        from_home: "Từ nhà",
        view_details: "Chi tiết",
        address_suggestion: "Gợi ý địa chỉ",
        place_name: "Tên địa điểm",
        address: "Địa chỉ",
        add_suggestion: "Thêm gợi ý",
        location_details: "Chi tiết địa điểm",
        opening_hours: "Giờ mở cửa",
        personal_info: "Thông tin cá nhân",
        system_config: "Cấu hình hệ thống",
        general_info: "Thông tin chung",
        home_address: "Địa chỉ nhà",
        office_address: "Địa chỉ văn phòng",
        security_and_account: "Bảo mật & Tài khoản",
        general_settings: "Cài đặt chung",
        setting: "Cài đặt",
        language: "Ngôn ngữ",
        sign_out: "Đăng xuất",
        confirm: "Xác nhận",
        username: "Tên đăng nhập",
        actions: "Hành động",
        edit: "Sửa",
        delete: "Xóa",
        server_error: "Đã xảy ra lỗi máy chủ",
        sending: "Đang gửi...",
        error_creating_filter_place: "Lỗi khi tạo địa điểm lọc",
        confirm_delete: "Bạn có chắc chắn muốn xóa không?",
        delete_filter_place_success: "Xóa địa điểm lọc thành công",
        delete_filter_place_error: "Lỗi khi xóa địa điểm lọc",
        otp_sent_to_email: "OTP đã được gửi đến email của bạn!",
        email_not_registered: "Địa chỉ email này chưa được đăng ký",
        too_many_requests: "Quá nhiều yêu cầu. Vui lòng thử lại sau",
        check_internet_connection: "Vui lòng kiểm tra kết nối internet",
        enter_6_digit_otp: "Vui lòng nhập mã OTP gồm 6 chữ số",
        otp_verification_success: "Xác minh OTP thành công!",
        otp_expired: "OTP đã hết hạn. Vui lòng gửi lại",
        otp_invalid: "OTP không hợp lệ. Vui lòng thử lại",
        otp_verification_failed: "Xác minh OTP thất bại",
        authenticating: "Đang xác thực...",
        please_fill_all_fields: "Vui lòng điền vào tất cả các trường",
        login_success: "Đăng nhập thành công",
        login_failed: "Đăng nhập thất bại",
        cant_get_current_location: "Không thể lấy vị trí hiện tại.",
        cant_find_location: "Không thể tìm thấy vị trí.",
        cant_find_activity: (activity) => `Không tìm thấy địa điểm ${activity} nào quanh khu vực này.`,
        get_place_details_error: "Không thể lấy chi tiết địa điểm.",
        getting_place_details: "Đang lấy chi tiết địa điểm...",
        mon_to_sun: "Thứ Hai - Chủ Nhật",
        password_min_length: "Mật khẩu phải có ít nhất 6 ký tự",
        register_success: "Đăng ký thành công",
        register_failed: "Đăng ký thất bại",
        session_invalid: "Phiên đăng nhập không hợp lệ. Vui lòng bắt đầu lại.",
        strong_password: "Mật khẩu phải bao gồm số, chữ cái và ký tự đặc biệt.",
        include_alphabets: "Bao gồm chữ cái",
        include_numbers: "Bao gồm số",
        include_special_characters: "Bao gồm ký tự đặc biệt (!@#$%^&*)",
        password_match: "Mật khẩu khớp nhau",
        reseting_password: "Đang đặt lại mật khẩu...",
        cant_get_user_info: "Không thể lấy thông tin người dùng.",
        user_profile_updated_success: "Cập nhật hồ sơ thành công",
        user_profile_updated_failed: "Cập nhật hồ sơ thất bại",
        please_select_image: "Vui lòng chọn một hình ảnh",
        image_max_size: "Vui lòng chọn hình ảnh dưới 5MB",
        error_getting_filter_place: "Lỗi khi lấy địa điểm lọc",
        error_getting_suggestion_places: "Lỗi khi lấy danh sách gợi ý",
        searching_places: "Đang tìm kiếm địa điểm...",
        please_select_filter_place: "Vui lòng chọn một địa điểm",
        no_suggestions: "Không có gợi ý nào",
        error_getting_user_list: "Lỗi khi lấy danh sách người dùng",
        error_updating_user_profile: "Lỗi khi cập nhật hồ sơ người dùng",
        error_deleting_user: "Lỗi khi xóa người dùng",
        delete_user_success: "Xóa người dùng thành công",
        getting_user_list: "Đang lấy danh sách người dùng...",
        no_name: "Chưa có tên",
        need_login: "Bạn cần đăng nhập để truy cập trang này.",
        page_not_found: "Không tìm thấy trang",
        go_back: "Quay lại",
        page_not_found_message: "Trang bạn đang tìm kiếm không tồn tại hoặc có thể đã bị di chuyển hoặc xóa.",
        loading_data: "Đang tải dữ liệu...",
        find_places: (number) => `Tìm thấy ${number} địa điểm quanh bạn`,
        error_finding_places: "Lỗi khi tìm địa điểm",
    },
    en: {
        welcome: "Welcome to the FreeTime Spots project",
        login: "Login",
        email: "Email Address",
        password: "Password",
        confirm_password: "Confirm Password",
        forgot_password: "Forgot Password?",
        reset_password: "Reset Password",
        reset_password_failed: "Reset Password Failed",
        new_password: "New Password",
        change_password: "Change Password",
        register: "Register",
        don_t_have_account: "Don't have an account?",
        already_have_account: "Already have an account?",
        please_enter_email: "Please enter the email address associated with your account.",
        otp_note: "An OTP code will be sent to your registered email address.",
        get_otp: "Get OTP Code",
        get_otp_failed: "Failed to get OTP code",
        invalid_otp: "Invalid OTP",
        home: "Home",
        schedule: "Schedule",
        map: "Map",
        my_page: "My Page",
        check_email: "Please check your email",
        enter_otp_sent_to: (email) => `Enter the OTP code sent to ${email}`,
        verify: "Verify",
        did_not_receive_code: "Did not receive the code?",
        resend_code: "Resend Code",
        enter_new_password: "Enter your new password",
        remember_password: "Remembered your password? ",
        change_password_success: "Password changed successfully",
        change_password_failed: "Password change failed",
        change_password_process_success: "Password reset process completed successfully",
        password_not_match: "Confirm password does not match the new password",
        back_to_login: "Back to Login",
        where_you_go: "Where are you going? ",
        more: "Show more",
        less: "Show less",
        gym: "Gym",
        yoga: "Yoga",
        pilates: "Pilates",
        crossfit: "CrossFit",
        boxing: "Boxing",
        running: "Running",
        swimming: "Swimming",
        cycling: "Cycling",
        bouldering: "Bouldering",
        golf: "Golf",
        badminton: "Badminton",
        tennis: "Tennis",
        table_tennis: "Table Tennis",
        basketball: "Basketball",
        soccer: "Soccer",
        volleyball: "Volleyball",
        suggest_list: "Suggestion List",
        order: "Order",
        search: "Search",
        type: "Type",
        distance: "Distance",
        from_work: "From Work",
        from_home: "From Home",
        view_details: "Details",
        address_suggestion: "Address Suggestion",
        place_name: "Place Name",
        address: "Address",
        add_suggestion: "Add Suggestion",
        location_details: "Location Details",
        opening_hours: "Opening Hours",
        personal_info: "Personal Information",
        system_config: "System Configuration",
        general_info: "General Information",
        home_address: "Home Address",
        office_address: "Office Address",
        security_and_account: "Security & Account",
        general_settings: "General Settings",
        setting: "Setting",
        language: "Language",
        sign_out: "Sign Out",
        confirm: "Confirm",
        username: "Username",
        actions: "Actions",
        edit: "Edit",
        delete: "Delete",
        server_error: "A server error has occurred",
        sending: "Sending...",
        error_creating_filter_place: "Error creating filter place",
        confirm_delete: "Are you sure you want to delete?",
        delete_filter_place_success: "Delete filter place successfully",
        delete_filter_place_error: "Error deleting filter place",
        otp_sent_to_email: "OTP has been sent to your email!",
        email_not_registered: "This email address is not registered",
        too_many_requests: "Too many requests. Please try again later",
        check_internet_connection: "Please check your internet connection",
        enter_6_digit_otp: "Please enter the 6-digit OTP code",
        otp_verification_success: "OTP verification successful!",
        otp_expired: "OTP has expired. Please resend",
        otp_invalid: "Invalid OTP. Please try again",
        otp_verification_failed: "OTP verification failed",
        authenticating: "Authenticating...",
        please_fill_all_fields: "Please fill in all fields",
        login_success: "Login successful",
        login_failed: "Login failed",
        cant_get_current_location: "Can't get current location.",
        cant_find_location: "Can't find location.",
        cant_find_activity: (activity) => `No ${activity} places found around this area.`,
        get_place_details_error: "Can't get place details.",
        getting_place_details: "Getting place details...",
        mon_to_sun: "Monday - Sunday",
        password_min_length: "Password must be at least 6 characters long",
        register_success: "Registration successful",
        register_failed: "Registration failed",
        session_invalid: "Session is invalid. Please start over.",
        strong_password: "Password must include numbers, letters, and special characters.",
        include_alphabets: "Include alphabets",
        include_numbers: "Include numbers",
        include_special_characters: "Include special characters (!@#$%^&*)",
        password_match: "Passwords match",
        reseting_password: "Resetting Password...",
        cant_get_user_info: "Can't get user information.",
        user_profile_updated_success: "User profile updated successfully",
        user_profile_updated_failed: "User profile update failed",
        please_select_image: "Please select an image",
        image_max_size: "Please select an image under 5MB",
        error_getting_filter_place: "Error getting filter place",
        error_getting_suggestion_places: "Error getting suggestion list",
        searching_places: "Searching places...",
        please_select_filter_place: "Please select a place",
        no_suggestions: "No suggestions available",
        error_getting_user_list: "Error getting user list",
        error_updating_user_profile: "Error updating user profile",
        error_deleting_user: "Error deleting user",
        delete_user_success: "User deleted successfully",
        getting_user_list: "Getting user list...",
        no_name: "No name",
        need_login: "You need to log in to access this page.",
        page_not_found: "Page Not Found",
        go_back: "Go back",
        page_not_found_message: "The page you are looking for does not exist or may have been moved or deleted.",
        loading_data: "Loading data...",
        find_places: (number) => `Found ${number} spots around you`,
        error_finding_places: "Error finding places",
    },
    jp: {
        welcome: "FreeTime Spotsプロジェクトへようこそ",
        login: "ログイン",
        email: "メールアドレス",
        password: "パスワード",
        confirm_password: "パスワード確認",
        forgot_password: "パスワードをお忘れの方?",
        reset_password: "パスワードの再設定",
        reset_password_failed: "パスワードの再設定に失敗しました",
        new_password: "新しいパスワード",
        change_password: "パスワードを変更する",
        register: "新規登録",
        don_t_have_account: "アカウントをお持ちでない方?",
        already_have_account: "既にアカウントをお持ちですか？",
        please_enter_email: "アカウントにご登録のメールアドレスを入力してください。",
        otp_note: "ご登録のメールアドレス宛に、認証コード（OTP）を送信します。",
        get_otp: "OTPコードを取得する",
        get_otp_failed: "OTPコードの取得に失敗しました",
        invalid_otp: "無効なOTPです",
        home: "ホーム",
        schedule: "スケジュール",
        map: "マップ",
        my_page: "マイページ",
        check_email: "メールをご確認ください",
        enter_otp_sent_to: (email) => `${email}に送信した認証コードを入力してください。`,
        verify: "認証する",
        did_not_receive_code: "認証コードが届かない場合?",
        resend_code: "認証コードを再送信",
        enter_new_password: "新しいパスワードを入力してください",
        remember_password: "パスワードを思い出しましたか？ ",
        change_password_success: "パスワードの変更が完了しました",
        change_password_failed: "パスワードの変更に失敗しました",
        change_password_process_success: "パスワードの再設定が正常に完了しました",
        password_not_match: "確認用パスワードが新しいパスワードと一致しません",
        back_to_login: "ログインページへ戻る",
        where_you_go: "どこへ行きますか? ",
        more: "もっと見る",
        less: "閉じる",
        gym: "ジム",
        yoga: "ヨガ",
        pilates: "ピラティス",
        crossfit: "クロスフィット",
        boxing: "ボクシング",
        running: "ランニング",
        swimming: "プール",
        cycling: "サイクリング",
        bouldering: "ボルダリング",
        golf: "ゴルフ",
        badminton: "バドミントン",
        tennis: "テニス",
        table_tennis: "卓球",
        basketball: "バスケ",
        soccer: "サッカー",
        volleyball: "バレーボール",
        suggest_list: "提案リスト",
        order: "順番",
        search: "検索",
        type: "タイプ",
        distance: "距離",
        from_work: "職場から",
        from_home: "自宅から",
        view_details: "細",
        address_suggestion: "住所の提案",
        place_name: "場所の名前",
        address: "住所",
        add_suggestion: "提案を追加",
        location_details: "場所の詳細",
        opening_hours: "営業時間",
        personal_info: "パーソナル情報",
        system_config: "システムコンフィギュレーション",
        general_info: "総合案内",
        home_address: "ホームアドレス",
        office_address: "事務所",
        security_and_account: "セキュリティとアカウント",
        general_settings: "一般設定",
        setting: "設定",
        language: "言語",
        sign_out: "サインアウト",
        confirm: "コンファーム",
        username: "ユーザー名",
        actions: "アクション",
        edit: "編集",
        delete: "削除",
        server_error: "サーバーエラーが発生しました",
        sending: "送信中...",
        error_creating_filter_place: "フィルタプレースの作成エラー",
        confirm_delete: "本当に削除しますか？",
        delete_filter_place_success: "フィルタプレースの削除に成功しました",
        delete_filter_place_error: "フィルタプレースの削除エラー",
        otp_sent_to_email: "OTPをメールに送信しました！",
        email_not_registered: "このメールアドレスは登録されていません",
        too_many_requests: "リクエストが多すぎます。しばらくお待ちください",
        check_internet_connection: "インターネット接続を確認してください",
        enter_6_digit_otp: "6桁のOTPコードを入力してください",
        otp_verification_success: "OTP認証に成功しました！",
        otp_expired: "OTPの有効期限が切れました。再送信してください",
        otp_invalid: "無効なOTPです。もう一度お試しください",
        otp_verification_failed: "OTPの認証に失敗しました",
        authenticating: "認証中...",
        please_fill_all_fields: "すべてのフィールドを入力してください",
        login_success: "ログイン成功しました",
        login_failed: "ログインに失敗しました",
        cant_get_current_location: "現在地を取得できません。",
        cant_find_location: "場所が見つかりません。",
        cant_find_activity: (activity) => `このエリアで${activity}のアクティビティが見つかりません。`,
        get_place_details_error: "場所の詳細を取得できません。",
        getting_place_details: "場所の詳細を取得しています...",
        mon_to_sun: "月曜日 - 日曜日",
        password_min_length: "パスワードは6文字以上である必要があります",
        register_success: "登録成功しました",
        register_failed: "登録に失敗しました",
        session_invalid: "セッションが無効です。最初からやり直してください。",
        strong_password: "パスワードは数字、文字、特殊文字を含める必要があります。",
        include_alphabets: "アルファベットを含む",
        include_numbers: "数字を含む",
        include_special_characters: "特殊文字を含む (!@#$%^&*)",
        password_match: "パスワードが一致します",
        reseting_password: "パスワードをリセットしています...",
        cant_get_user_info: "ユーザー情報を取得できません。",
        user_profile_updated_success: "ユーザープロフィールが正常に更新されました",
        user_profile_updated_failed: "ユーザープロフィールの更新に失敗しました",
        please_select_image: "画像を選択してください",
        image_max_size: "5MB以下の画像を選択してください",
        error_getting_filter_place: "フィルタプレースの取得エラー",
        error_getting_suggestion_places: "提案リストの取得エラー",
        searching_places: "場所を検索しています...",
        please_select_filter_place: "場所を選択してください",
        no_suggestions: "利用可能な提案はありません",
        error_getting_user_list: "ユーザーリストの取得エラー",
        error_updating_user_profile: "ユーザープロフィールの更新エラー",
        error_deleting_user: "ユーザーの削除エラー",
        delete_user_success: "ユーザーの削除に成功しました",
        getting_user_list: "ユーザーリストを取得しています...",
        no_name: "名前なし",
        need_login: "このページにアクセスするにはログインが必要です。",
        page_not_found: "ページが見つかりません",
        go_back: "戻る",
        page_not_found_message: "お探しのページは存在しないか、移動または削除された可能性があります。",
        loading_data: "データを読み込み中...",
        find_places: (number) => `周辺に${number}件のスポットを発見しました`,
        error_finding_places: "場所の検索エラー",
    }
}

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
    const [lang, setLang] = useState('en');

    const t = (key) => translations[lang][key] || key;

    return (
        <LanguageContext.Provider value={{ lang, setLang, t }}>
            {children}
        </LanguageContext.Provider>
    )
}

export const useLang = () => useContext(LanguageContext);