import React, { createContext, useState, useContext } from 'react'

const translations = {
    vi: {
        welcome: "Chào mừng đến với dự án FreeTime Spots",
        login: "Đăng nhập",
        email: "Địa chỉ Email",
        password: "Mật khẩu",
        confirm_password: "Xác nhận mật khẩu",
        forgot_password: "Quên mật khẩu?",
        reset_password: "Đặt lại mật khẩu",
        new_password: "Mật khẩu mới",
        change_password: "Đổi mật khẩu",
        register: "Đăng ký",
        don_t_have_account: "Chưa có tài khoản?",
        please_enter_email: "Vui lòng nhập địa chỉ email liên kết với tài khoản của bạn.",
        otp_note: "Mã OTP sẽ được gửi đến địa chỉ email đã đăng ký của bạn.",
        get_otp: "Lấy mã OTP",
        home: "Trang chủ",
        schedule: "Lịch trình",
        map: "Bản đồ",
        my_page: "Trang của tôi",
        check_email: "Vui lòng kiểm tra email của bạn",
        enter_otp_sent_to: "Nhập mã OTP đã gửi đến",
        verify: "Xác minh",
        did_not_receive_code: "Không nhận được mã?",
        resend_code: "Gửi lại mã",
        enter_new_password: "Nhập mật khẩu mới của bạn",
        remember_password: "Đã nhớ mật khẩu? ",
        change_password_success: "Đổi mật khẩu thành công",
        change_password_process_success: "Quá trình đặt lại mật khẩu hoàn tất thành công",
        back_to_login: "Quay lại đăng nhập",
        where_you_go: "Bạn sẽ đi đâu? ",
        more: "Xem thêm",
        less: "Thu gọn",
        gym: "Gym",
        yoga: "Yoga",
        pilates: "Pilates",
        crossfit: "Crossfit",
        boxing: "Boxing",
        running: "Chạy bộ",
        swimming: "Bơi lội",
        cycling: "Đạp xe",
        bouldering: "Leo núi trong nhà",
        golf: "Golf",
        badminton: "Cầu lông",
        tennis: "Tennis",
        table_tennis: "Bóng bàn",
        basketball: "Bóng rổ",
        soccer: "Bóng đá",
        volleyball: "Bóng chuyền",
        suggest_list: "Danh sách gợi ý",
        order: "Thứ tự",
        search: "Tìm kiếm",
        type: "Thể Loại",
        distance: "Khoảng cách",
        from_work: "Từ chỗ làm",
        from_home: "Từ nhà",
        view_details: "Chi tiết",
        address_suggestion: "Gợi ý địa chỉ",
        place_name: "Tên địa điểm",
        address: "Địa chỉ",
        add_suggestion: "Thêm gợi ý",
        location_details: "Chi tiết địa điểm",
        opening_hours: "Giờ mở cửa",
        personal_info: "Thông tin cá nhân",
        system_config: "Cấu hình hệ thống",
        general_info: "Thông tin chung",
        home_address: "Địa chỉ nhà",
        office_address: "Địa chỉ văn phòng",
        security_and_account: "Bảo mật & Tài khoản",
        general_settings: "Cài đặt chung",
        language: "Ngôn ngữ",
        sign_out: "Đăng xuất",
        confirm: "Xác nhận",
        username: "Tên đăng nhập",
        actions: "Hành động",
        edit: "Sửa",
        delete: "Xóa",
    },
    en: {
        welcome: "Welcome to the FreeTime Spots project",
        login: "Login",
        email: "Email Address",
        password: "Password",
        confirm_password: "Confirm Password",
        forgot_password: "Forgot Password?",
        reset_password: "Reset Password",
        new_password: "New Password",
        change_password: "Change Password",
        register: "Register",
        don_t_have_account: "Don't have an account?",
        please_enter_email: "Please enter the email address associated with your account.",
        otp_note: "An OTP code will be sent to your registered email address.",
        get_otp: "Get OTP Code",
        home: "Home",
        schedule: "Schedule",
        map: "Map",
        my_page: "My Page",
        check_email: "Please check your email",
        enter_otp_sent_to: "Enter the OTP code sent to",
        verify: "Verify",
        did_not_receive_code: "Did not receive the code?",
        resend_code: "Resend Code",
        enter_new_password: "Enter your new password",
        remember_password: "Remembered your password? ",
        change_password_success: "Password changed successfully",
        change_password_process_success: "Password reset process completed successfully",
        back_to_login: "Back to Login",
        where_you_go: "Where are you going? ",
        more: "Show more",
        less: "Show less",
        gym: "Gym",
        yoga: "Yoga",
        pilates: "Pilates",
        crossfit: "CrossFit",
        boxing: "Boxing",
        running: "Running",
        swimming: "Swimming",
        cycling: "Cycling",
        bouldering: "Bouldering",
        golf: "Golf",
        badminton: "Badminton",
        tennis: "Tennis",
        table_tennis: "Table Tennis",
        basketball: "Basketball",
        soccer: "Soccer",
        volleyball: "Volleyball",
        suggest_list: "Suggestion List",
        order: "Order",
        search: "Search",
        type: "Type",
        distance: "Distance",
        from_work: "From Work",
        from_home: "From Home",
        view_details: "Details",
        address_suggestion: "Address Suggestion",
        place_name: "Place Name",
        address: "Address",
        add_suggestion: "Add Suggestion",
        location_details: "Location Details",
        opening_hours: "Opening Hours",
        personal_info: "Personal Information",
        system_config: "System Configuration",
        general_info: "General Information",
        home_address: "Home Address",
        office_address: "Office Address",
        security_and_account: "Security & Account",
        general_settings: "General Settings",
        language: "Language",
        sign_out: "Sign Out",
        confirm: "Confirm",
        username: "Username",
        actions: "Actions",
        edit: "Edit",
        delete: "Delete",
    },
    jp: {
        welcome: "FreeTime Spotsプロジェクトへようこそ",
        login: "ログイン",
        email: "メールアドレス",
        password: "パスワード",
        confirm_password: "パスワード確認",
        forgot_password: "パスワードをお忘れの方?",
        reset_password: "パスワードの再設定",
        new_password: "新しいパスワード",
        change_password: "パスワードを変更する",
        register: "新規登録",
        don_t_have_account: "アカウントをお持ちでない方?",
        please_enter_email: "アカウントにご登録のメールアドレスを入力してください。",
        otp_note: "ご登録のメールアドレス宛に、認証コード（OTP）を送信します。",
        get_otp: "OTPコードを取得する",
        home: "ホーム",
        schedule: "スケジュール",
        map: "マップ",
        my_page: "マイページ",
        check_email: "メールをご確認ください",
        enter_otp_sent_to: "に送信した認証コードを入力してください。",
        verify: "認証する",
        did_not_receive_code: "認証コードが届かない場合?",
        resend_code: "認証コードを再送信",
        enter_new_password: "新しいパスワードを入力してください",
        remember_password: "パスワードを思い出しましたか？ ",
        change_password_success: "パスワードの変更が完了しました",
        change_password_process_success: "パスワードの再設定が正常に完了しました",
        back_to_login: "ログインページへ戻る",
        where_you_go: "どこへ行きますか? ",
        more: "もっと見る",
        less: "閉じる",
        gym: "ジム",
        yoga: "ヨガ",
        pilates: "ピラティス",
        crossfit: "クロスフィット",
        boxing: "ボクシング",
        running: "ランニング",
        swimming: "プール",
        cycling: "サイクリング",
        bouldering: "ボルダリング",
        golf: "ゴルフ",
        badminton: "バドミントン",
        tennis: "テニス",
        table_tennis: "卓球",
        basketball: "バスケ",
        soccer: "サッカー",
        volleyball: "バレーボール",
        suggest_list: "提案リスト",
        order: "順番",
        search: "検索",
        type: "タイプ",
        distance: "距離",
        from_work: "職場から",
        from_home: "自宅から",
        view_details: "細",
        address_suggestion: "住所の提案",
        place_name: "場所の名前",
        address: "住所",
        add_suggestion: "提案を追加",
        location_details: "場所の詳細",
        opening_hours: "営業時間",
        personal_info: "パーソナル情報",
        system_config: "システムコンフィギュレーション",
        general_info: "総合案内",
        home_address: "ホームアドレス",
        office_address: "事務所",
        security_and_account: "セキュリティとアカウント",
        general_settings: "一般設定",
        language: "言語",
        sign_out: "サインアウト",
        confirm: "コンファーム",
        username: "ユーザー名",
        actions: "アクション",
        edit: "編集",
        delete: "削除",
    }
}

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
    const [lang, setLang] = useState('jp');

    const t = (key) => translations[lang][key] || key;

    return (
        <LanguageContext.Provider value={{ lang, setLang, t }}>
            {children}
        </LanguageContext.Provider>
    )
}

export const useLang = () => useContext(LanguageContext);